### PR TITLE
Improved testing notebook for mass sink

### PR DESCRIPTION
**Pull request by fdf2002**
@hdrake I made a basic testing notebook in the **otec1d** example directory. It plots the height of each layer over time, then uses the change in height to reverse engineer W_OTEC. This test was successful with my single mass sink.

### CODE REVIEW

**Comment by hdrake** [comment]
The test on the thickness looks great Freddie and it seems the magnitude of the mass sink is working as intended.

**Comment by hdrake** [comment]
Do you know what's going on with the temperature plot in the [test.ipynb notebook](https://github.com/hdrake/MOM6-examples/blob/008b4bbe4700e5dc8263b87bdc3c3aac12c29602/ocean_only/otec1d/test.ipynb) though? It looks like the temperature jumps from near 0 (or maybe between 15 and 30) to 1e37? Maybe the model blows up at some point because your pumping velocity is big enough that it is the equivalent of removing a thickness of 432m from the water column by the end time of 5 days?

**Comment by hdrake** [comment]
It also seems like the upper layer around ~200m depth is missing from the layer thickness, maybe because it disappears? Can you check if it is indeed there at first and only disappears later on?

**Comment by fdf2002** [comment]
Regarding the upper layer, I think I may have not been clear: the plot shows the height of the _top_ of each layer over time. The top layer decreases in height by 432 m every 5 days; its height is 0 at initial conditions then decreases to -432 m on 01-06 (which is day 5). All 10 layers are shown at the expected heights.

As for temperature, thank you for returning that to my attention, I ignored it completely! That was from a previous run that only lasted 1 day. I'm now pushing an updated notebook with an updated temperature plot and a printed array of the initial depths.

On that note though, if I want to change how often data is written to the output file, how would I do that? Currently, I only get data for every 5 days from the start.

**Comment by hdrake** [comment]
> On that note though, if I want to change how often data is written to the output file, how would I do that? Currently, I only get data for every 5 days from the start. [@fdf2002]

You'll want to edit the `diag_table` file in the experiment folder. The comments at the end of the file explain the formatting—you can use it to change the frequency of output, the type of output (as a time-average between two consecutive outputs or just a snapshot at that timestep), and the diagnostic variables you want to output.

At somepoint down the line we'll probably want to make the mass of water that we pump and mix a new diagnostic of our own, which could also be output in this way!

**Comment by hdrake** [comment]
> Regarding the upper layer, I think I may have not been clear: the plot shows the height of the _top_ of each layer over time. The top layer decreases in height by 432 m every 5 days; its height is 0 at initial conditions then decreases to -432 m on 01-06 (which is day 5). All 10 layers are shown at the expected heights.

Thanks, that makes sense. I was confused because I didn't see the lines starting but now I realize the lines were just showing the trend from day 5 to 10, not 0 to 5 or 0 to 10. Having more output timesteps should help clarify this.

> As for temperature, thank you for returning that to my attention, I ignored it completely! That was from a previous run that only lasted 1 day. I'm now pushing an updated notebook with an updated temperature plot and a printed array of the initial depths.

It looks like setting a strictly positive diffusivity at least fixed the blow-up in the temperature—nice! I realize I was also confused because I hadn't realized you set the top-to-bottom temperature difference to zero.

https://github.com/hdrake/MOM6-examples/blob/70f416298a75c95d127be3e9c13ffab38df61e02/ocean_only/otec1d/with/MOM_input#L172-L175

Are you purposefully having a constant temperature in the whole column so that when you start messing with the temperatures due to OTEC you'll see the signal clearly? It might be worth at least putting a very small top-to-bottom temperature difference because the model might do funky things when it's in this state that is marginally stable to convective (gravitational) instability.

**Comment by fdf2002** [comment]
No, that was not intentional--I had originally meant for a temperature gradient from 25 to 0 C, a mistake I've made before, but I decided it was fine as it was. You do have a good point though, I'll try running it with a nonzero difference, both with and without the mass sink.

**Comment by hdrake** [comment]
See https://github.com/hdrake/MOM6-examples/pull/1#issuecomment-1175312950 for good syntax for spreading thickness changes and tracers fluxes over several layers (e.g. if initial layer vanishes).

**Comment by hdrake** [comment]
Just to recap our meeting @fdf2002:
- You had implemented a nice scheme for spreading the mass sink across layers (to deeper layers) to deal with the case of vanishing layer thickness.
- I remembered that part of the [`ApplyBoundaryFluxesInOut`](https://github.com/mom-ocean/MOM6/blob/4f6f9757f854de10f55b44dee4ba1f02dd25fb2d/src/parameterizations/vertical/MOM_diabatic_aux.F90#L1255-L1393) subroutine does a similar thing, so it would be good for us to follow their syntax and variable naming conventions for consistency. We can also learn from how they treat edge cases likes vanishing layer thickness, "grounding" (when all the layers vanish), etc.
- Based on this subroutine it seems like the mixing of the intake temperature and salinity and the dilution of the layer by the mixed discharge is best to be handled within the same subroutine as the mass source part.
- We discussed the fact that the "mixing" of the two intakes does not need to happen before the "dilution" step where they are both injected. This means the `otec_pipes` subroutine can be thought of as combination of two calls (in serial) to a more generalizable `vertical_pipe` routine.
- You will work on a "pseudo-code" of the `mass_sink`, `massTS_source`, `vertical_pipe`, and `otec_pipes` subsoutines, which follows the syntax and general approach of `ApplyBoundaryFluxesInOut`.

**Comment by fdf2002** [comment]
I tried turning off regridding for a new testing run since that will be helpful to visualize going forward. However, the output looks pretty broken in Jupyter, and mass is not actually being removed in that run. (I have not recompiled.)

**Comment by fdf2002** [comment]
Making sure this test works properly will be crucial to making sure that the OTEC module is operating correctly by reorganizing layers.

**Comment by hdrake** [comment]
I saw the `regridding_on` notebook but I don't think you added the `regridding_off` notebook that looks broken. Can you add that so I can take a look? 

Also, it might be helpful to change `diag_table` so that you have outputs every day, just so we can get a bit more resolution in these time-series plots.

**Comment by fdf2002** [comment]
Oh, I should have clarified--my notebook with regridding off was simply the "test.ipynb" notebook that was already there.

**Pull request merged**
